steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-image-name']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', 'nba-app', '--image', 'gcr.io/$PROJECT_ID/your-image-name', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
