steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -l && ls -l /app && cat requirements.txt'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']

images: ['gcr.io/$PROJECT_ID/your-image-name']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
