steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-image-name']

images:
  - 'gcr.io/$PROJECT_ID/your-image-name'

options:
  logging: CLOUD_LOGGING_ONLY
