steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/franciscodiazmolina/NBA', '.']

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls -l'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']
